### ISSUE TITLE
[Sugestia - nazwa]: 

### ISSUE THREAD

**Issue by jestemjaworr** [Thundo54/tablice-td2-api#2]
### Przewoźnik

Koleje Mazowieckie

### Numery pociągu

25137

### Nazwa pociągu

KAMIENNA

### Nadpisane kategorii

RE90

### Informacje o pociągu

Skarżysko-Kamienna (4:13) - Ciechanów (7:25), kursuje (1)-(5) - 1 XI

**Comment by Thundo54** [comment]
dodano w 022f2fb
