### ISSUE TITLE
[Sugestia - przewoźnik]: 

### ISSUE THREAD

**Issue by Gaclawek** [Thundo54/tablice-td2-api#3]
### Nazwa przewoźnika

InterCity

### Skrót nazwy przewoźnika

IC

### Początek numeru pociągów

10100/10101

### Skrót kategorii przewoźnika

TLK

### Informacje o przewoźniku

TLK Żubr

**Comment by Thundo54** [comment]
pociąg już istnieje w api
```       
 {
    "operator": "IC",
    "trainNo": ["10100", "10101", "10110", "10111"],
    "categoryOverwrite": "TLK",
    "trainName": "Żubr"
},
```
